In [ ]:
"""
import numpy as np

def generate_eigenvector_dict():
    num_epochs = 10
    dim = 10  # 向量维度
    recorded_steps_top_eigenvectors = {}

    # 生成一个初始的正交基（使用单位矩阵，确保正交）
    base_vectors = np.eye(dim)  # 10×5 单位矩阵，每列是一个标准正交向量
    
    for k in range(num_epochs):
        if k == 0:
            recorded_steps_top_eigenvectors[k] = base_vectors.copy()
        else:
            # 继承前一个 epoch 的部分特征向量
            num_shared = max(dim - k, 0)  # 计算要保留的列数
            new_vectors = np.random.randn(dim, k)  # 生成新的列向量
            
            # 重新进行正交化，保证新的基是正交的
            Q, _ = np.linalg.qr(np.hstack((recorded_steps_top_eigenvectors[k-1][:, :num_shared], new_vectors)))
            recorded_steps_top_eigenvectors[k] = Q  # 存入字典
    
    return recorded_steps_top_eigenvectors

# 生成特征向量字典
recorded_steps_top_eigenvectors = generate_eigenvector_dict()

# 打印前 3 个 epoch 的特征矩阵
for epoch in range(5):
    print(f"Epoch {epoch} 特征矩阵:\n", recorded_steps_top_eigenvectors[epoch], "\n")
"""


Epoch 0 特征矩阵:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]] 

Epoch 1 特征矩阵:
 [[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0. -0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [-0. -0. -0.  1.  0.  0.  0.  0.  0.  0.]
 [-0. -0. -0. -0.  1.  0.  0.  0.  0.  0.]
 [-0. -0. -0. -0. -0.  1.  0.  0.  0.  0.]
 [-0. -0. -0. -0. -0. -0.  1.  0.  0.  0.]
 [-0. -0. -0. -0. -0. -0. -0.  1.  0.  0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.  1.  0.]
 [-0. -0. -0. -0. -0. -0. -0. -0. -0.  1.]] 

Epoch 2 特征矩阵:
 [[ 1.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          1.          0.          0.          0.          0.
   0. 

Depricate previous code.

Generate a dictionary of top k eigenvectors for each epoch.

In [1]:
import numpy as np

# 设置 NumPy 随机种子
np.random.seed(42)

def generate_eigenvector_dict():
    num_epochs = 3  # 迭代次数
    dim = 10  # 向量维度
    num_vectors = 5  # 始终保持 5 个特征向量
    recorded_steps_top_eigenvectors = {}

    # 生成一个初始的正交基（使用 QR 分解确保正交）
    base_vectors, _ = np.linalg.qr(np.random.randn(dim, num_vectors))  # 10 × 5 的正交矩阵
    
    for k in range(num_epochs):
        if k == 0:
            recorded_steps_top_eigenvectors[k] = base_vectors.copy()
        else:
            # 计算要保留的列数
            num_shared = max(num_vectors - k, 0)    # 计算需要保留的特征向量数量
            num_new = num_vectors - num_shared  # 计算需要替换的特征向量数量
            
            # 继承前一个 epoch 的部分特征向量
            shared_vectors = recorded_steps_top_eigenvectors[k-1][:, :num_shared] if num_shared > 0 else np.empty((dim, 0))
            
            # 生成新的特征向量
            new_vectors = np.random.randn(dim, num_new)
            
            # 组合最终的特征矩阵
            recorded_steps_top_eigenvectors[k], _ = np.linalg.qr(np.hstack((shared_vectors, new_vectors)))  # QR分解，前几列已经正交，不会改变

    return recorded_steps_top_eigenvectors

# 生成特征向量字典
recorded_steps_top_eigenvectors = generate_eigenvector_dict()

# 打印前 ? 个 epoch 的特征矩阵
for epoch in range(3):
    print(f"Epoch {epoch} 特征矩阵:\n", recorded_steps_top_eigenvectors[epoch], "\n")


Epoch 0 特征矩阵:
 [[-0.20433962  0.01774928 -0.21280398  0.35336356  0.21267685]
 [ 0.0963199  -0.52254612 -0.37396241 -0.200287   -0.09229253]
 [ 0.19064203  0.18541408 -0.13898791 -0.56814509  0.1919557 ]
 [ 0.23131538  0.37702749 -0.16801856 -0.27        0.05892778]
 [-0.60294259 -0.00950348  0.13019713 -0.53376948 -0.02739447]
 [-0.04563164  0.38436437 -0.1200868  -0.23065281 -0.40864833]
 [ 0.24753171 -0.59366849 -0.09533138 -0.268181   -0.06648195]
 [ 0.50223399  0.00085284  0.67768789 -0.10739636  0.16728233]
 [-0.3037924  -0.10161923  0.12161616 -0.12750935  0.73237177]
 [ 0.29613147  0.1987628  -0.5027993   0.03881013  0.41160129]] 

Epoch 1 特征矩阵:
 [[-0.20433962  0.01774928 -0.21280398  0.35336356  0.02923768]
 [ 0.0963199  -0.52254612 -0.37396241 -0.200287    0.13338619]
 [ 0.19064203  0.18541408 -0.13898791 -0.56814509 -0.61109847]
 [ 0.23131538  0.37702749 -0.16801856 -0.27        0.15475094]
 [-0.60294259 -0.00950348  0.13019713 -0.53376948  0.34686508]
 [-0.04563164  0.38436

In [2]:
print(len(recorded_steps_top_eigenvectors))

3


In [9]:
import numpy as np
# import wandb

def Top_K_Search(recorded_steps_top_eigenvectors):
    
    sorted_steps = sorted(recorded_steps_top_eigenvectors.keys())  # Epoch
    num_steps = len(sorted_steps)
    
    if num_steps < 2:
        raise ValueError("At least two recorded steps are required for Top-K search.")
    
    # Initialize k
    k = recorded_steps_top_eigenvectors[sorted_steps[0]].shape[1]  # Number of columns
    # k = k_0
    tau = 0.98 # Tolerance
    
    for i in range(num_steps):
        current_step = sorted_steps[i]
        current = recorded_steps_top_eigenvectors[current_step][:, :k]   # Current top k eigenvectors
        if i > 0:
            previous_step = sorted_steps[i - 1]
            previous = recorded_steps_top_eigenvectors[previous_step][:,:k]  # Previous top k eigenvectors
            
            #  = np.concatenate((np.real(current), np.real(previous)), axis=1)  
            # matrix = np.matmul(combined_vectors.T, combined_vectors)  
            # eigenvalues = np.linalg.eigvalsh(matrix)
            # sorted_eigenvalues = np.sort(eigenvalues)[::-1]   # Decreasing order, not bigger than 2
            
            for d in range(k):
                
                current_subspace = current[:, :d+1]  # Current subspace
                previous_subspace = previous[:, :d+1]  # Previous subspace
                
                # Compute the similarity between the current and previous subspaces
                matrix = np.matmul(current_subspace.T, previous_subspace)
                _, sigma, _ = np.linalg.svd(matrix)
                
                # Check if all singular values are within [0, 1]
                assert np.all((sigma >= -0.001) & (sigma <= 1.001)), "Eigenvectors are not ortho-normalized!"
                
                min_sigma = np.min(sigma)
                
                if min_sigma < tau:
                    k = d
                    break

    return k

k = Top_K_Search(recorded_steps_top_eigenvectors)

print(k)    
        
        


3
